# Generated by Django 4.0.1 on 2022-01-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_delete_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='host',
        ),
    ]
